### ISSUE TITLE
dangerouslySetInnerHTML doesn't work

### ISSUE THREAD

**Issue by mrcnk** [nikolovlazar/chakra-ui-prose#12]
Hi, I'd like to use [chakra-ui-prose](https://github.com/nikolovlazar/chakra-ui-prose) to render contents coming from Strapi CMS to Next.js app as string with HTML. Unfortunately `dangerouslySetInnerHTML` doesn't work and I can't render it. I tried sorting this out myself, but I get various misuse of React Hooks errors when I'm trying to build the library locally (React versions are the same).

[Here's what I tried](https://github.com/mvr-studio/chakra-ui-prose/blob/main/packages/chakra-ui-prose/src/prose.tsx)

**Comment by nikolovlazar** [comment]
Hi @mrcnk! You could try adding a `Box` component (or an ordinary `div` element) inside of the `Prose` component and set the `dangerouslySetInnerHTML` to it instead. Don't forget to sanitize your content before rendering it! I'll update the guide with this info very soon. Thank you for pointing this out 🙏
