### ISSUE TITLE
Skip selected part of HTML

### ISSUE THREAD

**Issue by krzysztofMlczk** [nikolovlazar/chakra-ui-prose#24]
I would like to be able to skip certain parts of the HTML. E.g. something wrapped in a 
`<div class='skip-prose-styling'></div>`
would not be styled with prose styles, but rather with chakra theme (that excludes prose stylings)
Is it possible. If yes how can I work this out?

**Comment by nikolovlazar** [comment]
That's an interesting feature, @krzysztofMlczk. I guess you can use the override feature to set `all: 'unset'` to all of the children of a specific class like so:

```typescript
withProse({
   baseStyle: {
      '.skip-prose-styling > *': {
         all: 'unset',
      }
   }
})
```

Here's a fork from the original CodeSandbox that does exactly that: https://codesandbox.io/s/chakra-ui-prose-forked-cwry7h?file=/src/index.tsx.
