### ISSUE TITLE
Converting markdown html to chakra-ui? or a set of styles to overrule basic elements

### ISSUE THREAD

**Issue by Jarrodsz** [nikolovlazar/chakra-ui-prose#25]
My excuse if this is not the right place to ask this question but I literally could not find anywhere or other feasible solutions to render markdown html or html in that matter as chakra-ui.

So I tried prose and its great but now I have to manually set styles beside my chakra-ui theme to format the html. I find it unbelievable there seems to be no solid solution to convert html to chakra-ui and since prose is really nice it still is not really a 'clean' solution because on have to define all the styles.

For example I render a blog post from markdown with some bullet list and general html elements but for example the padding between the bullets is to high.

Is there perhaps a feasable solution to convert html to chakra-ui markup?
Again I know this is not perhaps the right place to ask but could not find any pointers to get in the right direction.

Using Prose If i fiddle with the styles enough I could get a acceptable solution but this feels very unclean to me, one would want to set styling 1 time in the chakra-ui theme and use that everywhere.

**Comment by nikolovlazar** [comment]
No it's okay @Jarrodsz. You can't really put the markdown styles into Chakra's theme without either creating a component, or messing up the theme 😁 This package takes the first approach. It creates a component that loads the markdown styles in a scoped way. You still provide the styles to the theme 1 time. If you wanted to put the markdown styles literally in your theme, then you'd have to implement this package manually in your app.

**Comment by Jarrodsz** [comment]
I see this seems to be the only solid solution to do it sorry for my noviceness.

I could not find it in the docs but would it be possible to inherit styles from the chakra-ui theme?

```
baseStyle: {
      h1: {
        fontSize: "inherit"
      },
```

If this would be possible I would only have to define styles only once and Prose could be a good solution.

**Comment by nikolovlazar** [comment]
I don't think you can. If you'd use the `Heading` for titles, you'd have to spread the Heading style of the specific size into the styles of the `h1` specific heading element.
